// What Problem: We need to read the shared theme JSON files and emit CSS
// custom properties that reveal.js recognizes (--r-* vars) plus mdslidepal-
// scoped vars (--mdp-*). This bridges the shared theme contract to reveal.js.
//
// How & Why: Pure functions — loadTheme reads JSON, themeToCss emits a CSS
// string. No CSS-in-JS runtime, no build tool dependency. The CSS is written
// once at build time to output/theme.css. Chose reveal.js's documented custom
// property names so we override the default theme cleanly.
//
// Written: 2026-04-12 during mdslidepal-web Iteration 1

import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import type { Theme } from "./types.js";

/**
 * Load a theme JSON file by name from the shared themes directory.
 * @param name Theme name (e.g., "agency-default")
 * @param themesDir Optional override for themes directory path
 */
export async function loadTheme(name: string, themesDir?: string): Promise<Theme> {
  const dir = themesDir ?? resolve(
    import.meta.dirname,
    "..",
    "..",
    "..",
    "..",
    "claude",
    "workstreams",
    "mdslidepal",
    "themes"
  );
  const filePath = resolve(dir, `${name}.json`);
  const raw = await readFile(filePath, "utf-8");
  const parsed = JSON.parse(raw) as Theme;

  // Basic structural validation — check required top-level fields
  const required = ["name", "colors", "fonts", "heading_scale", "body_size", "slide_padding"] as const;
  for (const field of required) {
    if (parsed[field] === undefined) {
      throw new Error(`Theme "${name}" is missing required field: ${field}`);
    }
  }
  if (!parsed.colors?.background || !parsed.colors?.foreground) {
    throw new Error(`Theme "${name}" is missing required color fields (background, foreground)`);
  }

  return parsed;
}

/**
 * Convert a Theme object to a CSS string with reveal.js custom properties
 * and mdslidepal-scoped variables.
 */
export function themeToCss(theme: Theme): string {
  const { colors, fonts, heading_scale, body_size, line_height, slide_padding, code_theme } = theme;

  return `/* Generated by mdslidepal from theme: ${theme.name} v${theme.version} */
:root {
  /* reveal.js recognized custom properties */
  --r-main-font: ${fonts.sans_family};
  --r-heading-font: ${fonts.display_family};
  --r-code-font: ${fonts.mono_family};
  --r-main-font-size: ${body_size}px;
  --r-main-color: ${colors.foreground};
  --r-heading-color: ${colors.foreground};
  --r-link-color: ${colors.link};
  --r-link-color-hover: ${colors.accent};
  --r-selection-background-color: ${colors.accent};
  --r-background-color: ${colors.background};

  /* mdslidepal-scoped variables */
  --mdp-code-bg: ${colors.code_background};
  --mdp-code-border: ${colors.code_border};
  --mdp-border: ${colors.border};
  --mdp-muted: ${colors.muted};
  --mdp-subtle: ${colors.subtle};
  --mdp-accent: ${colors.accent};
}

/* Heading sizes from theme scale */
.reveal h1 { font-size: ${heading_scale.h1}px; }
.reveal h2 { font-size: ${heading_scale.h2}px; }
.reveal h3 { font-size: ${heading_scale.h3}px; }
.reveal h4 { font-size: ${heading_scale.h4}px; }
.reveal h5 { font-size: ${heading_scale.h5}px; }
.reveal h6 { font-size: ${heading_scale.h6}px; }

/* Typography */
.reveal h1,
.reveal h2,
.reveal h3,
.reveal h4,
.reveal h5,
.reveal h6 {
  text-transform: none;
  letter-spacing: -0.01em;
}

.reveal {
  font-size: ${body_size}px;
  line-height: ${line_height};
}

/* Slide padding */
.reveal .slides section {
  padding: ${slide_padding.top}px ${slide_padding.right}px ${slide_padding.bottom}px ${slide_padding.left}px;
  box-sizing: border-box;
}

/* Background */
.reveal .slide-background {
  background-color: ${colors.background};
}

/* Code blocks */
.reveal pre {
  box-shadow: none;
  background: ${colors.code_background};
  border: 1px solid ${colors.code_border};
  border-radius: 6px;
  padding: 16px;
  font-size: 0.55em;
}

.reveal pre code {
  background: transparent;
  padding: 0;
  line-height: 1.5;
}

/* Inline code */
.reveal code {
  background: ${colors.code_background};
  border: 1px solid ${colors.code_border};
  border-radius: 3px;
  padding: 2px 6px;
  font-size: 0.85em;
}

.reveal pre code {
  border: none;
  border-radius: 0;
  padding: 0;
}

/* Tables */
.reveal table {
  border-collapse: collapse;
  margin: 1em auto;
}

.reveal table th,
.reveal table td {
  border: 1px solid ${colors.border};
  padding: 8px 16px;
  text-align: left;
}

.reveal table th {
  background: ${colors.subtle};
  font-weight: 600;
}

/* Task list checkboxes */
.reveal ul.contains-task-list {
  list-style: none;
  padding-left: 0;
}

.reveal li.task-list-item {
  list-style: none;
}

/* Links */
.reveal a {
  text-decoration: underline;
}

/* Strikethrough */
.reveal del {
  text-decoration: line-through;
  color: ${colors.muted};
}

/* Images */
.reveal img {
  max-width: 100%;
  max-height: 60vh;
  object-fit: contain;
}
`;
}
